FROM alpine:latest

CMD /bin/sh

# 1. build with followng command
# docker build -t basic-docker:latest .

# 2. Confirm an image named basic-docker:latest was created
# docker images

# 3. Run the image, exit out
# docker run -it basic-docker:latest /bin/sh

# 4. Look at the bizarre name
# docker ps --all

# 5. Run the image with a specific name
# docker run -it --name my-first-container basic-docker:latest /bin/sh

